### PR TITLE
LilyPond checker

### PR DESCRIPTION
**Pull request by dragn**
Basic syntax checker for [GNU LilyPond](http://lilypond.org/)

### CODE REVIEW

**Comment by lcd047** [comment]
Sorry, but this is naive.  Take for example `init.ly` from LilyPond's sources:
```
$ lilypond --loglevel=WARNING -dno-print-pages init.ly 
/usr/share/lilypond/2.18.2/ly/init.ly:40:1: error: \maininput not allowed outside init files

\maininput
/usr/share/lilypond/2.18.2/ly/init.ly:1: warning: no \version statement found, please add

\version "2.18.2"

for future compatibility
/usr/share/lilypond/2.18.2/ly/init.ly:1: warning: no \version statement found, please add

\version "2.18.2"

for future compatibility
fatal error: failed files: "init.ly"
```
Good luck turning it into something useful with `errorformat`.  In fact, looking at the sources, LilyPond's error handling is an even bigger mess than that of [elixir](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/exception.ex).  It's really, really not meant to be parsed.  You'd probably have a hard time coming up with something more hostile to parsing if you tried.

**Comment by dragn** [comment]
Thought so. I've only started to work with LilyPond, but this checker was
already proven useful to me. The problem I see so far is warnings that span
multiple lines. Perhaps I will encounter more peculiarities later, or look
into sources. What I like to say is that this basic checker is better then
nothing, and certainly enough for something to start with.

On Wed, 16 Sep 2015 10:00 am LCD 047 <notifications@github.com> wrote:

> Sorry, but this is naive. Take for example init.ly from LilyPond's
> sources:
>
> $ lilypond --loglevel=WARNING -dno-print-pages init.ly
> /usr/share/lilypond/2.18.2/ly/init.ly:40:1: error: \maininput not allowed outside init files
>
> \maininput
> /usr/share/lilypond/2.18.2/ly/init.ly:1: warning: no \version statement found, please add
>
> \version "2.18.2"
>
> for future compatibility
> /usr/share/lilypond/2.18.2/ly/init.ly:1: warning: no \version statement found, please add
>
> \version "2.18.2"
>
> for future compatibility
> fatal error: failed files: "init.ly"
>
> Good luck turning it into something useful with errorformat. In fact,
> looking at the sources, LilyPond's error handling is an even bigger mess
> than that of elixir
> <https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/exception.ex>.
> It's really, really not meant to be parsed. You'd probably have a hard time
> coming up with something more hostile to parsing if you tried.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scrooloose/syntastic/pull/1549#issuecomment-140648926>
> .
>
-- 
Best Regards,
Daniel

**Comment by lcd047** [comment]
Sadly, useful to you is not the same as trouble-free for me as a maintainer.  In an RPG game this would be the bottomless bag of bug reports. :) Fortunately you can maintain it as an [external checker](https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide#external).

**Comment by dragn** [comment]
Alright, seems fair. Thanks for your time reviewing this PR!

**Pull request closed without merging**
