### PR TITLE
pylama: requires '--force' if the file does not end in .py

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/klen/pylama/pull/35

### CODE REVIEW

**Comment by lcd047** [comment]
This is not enough: option `--force` seems to have appeared in pylama version 4.0.

**Comment by blueyed** [comment]
Oh.. this would require a version detection in Syntastic?

Then I'd wait for the outcome of https://github.com/klen/pylama/pull/35, and not add `--force` with Syntastic, if it would be fixed with a recent pylama.

**Comment by lcd047** [comment]
> Oh.. this would require a version detection in Syntastic?

Yup.

**Comment by lcd047** [comment]
There doesn't seem to be much interest in fixing this upstream, so I went ahead and did it anyway in 0470fff.

**Comment by blueyed** [comment]
Thanks!

**Pull request closed without merging**
