### PR TITLE
Use shellcheck checker for zsh.

### PR DESCRIPTION
**Pull request by paulhybryant**
Use shellcheck checker for zsh.

### CODE REVIEW

**Comment by lcd047** [comment]
This is backwards.  Once upon a time, shellcheck supported zsh syntax, syntastic supported checking zsh files with shellcheck, and everybody was happy.  Then shellcheck dropped support for zsh, and consequently syntastic had to drop support for the `shellcheck` checker for zsh.  Sorry, but no.

**Comment by paulhybryant** [comment]
Sure. I want to add it as external checkers in my own plugin.
I tried following https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide#external but didn't get it working.
I think that is because zsh is already a known filetype?
Is there a way to extend the checkers for a known filetype as weel?

Thanks,

**Comment by lcd047** [comment]
Just add [this file](https://raw.githubusercontent.com/scrooloose/syntastic/ebfba7ec3d52c804f3723ec336b1967b6ab5e37a/syntax_checkers/zsh/shellcheck.vim) to your plugin as `syntax_checkers/zsh/shellcheck.vim`.

**Comment by paulhybryant** [comment]
Thanks for the reply.
But I would like to pass additional arguments to shellcheck (specifically
-s bash) instead of redirecting.
The shellcheck argument in sh.vim doesn't specify a shell.

On Fri, Sep 11, 2015 at 3:20 PM, LCD 047 <notifications@github.com> wrote:

> Just add this file
> <https://raw.githubusercontent.com/scrooloose/syntastic/ebfba7ec3d52c804f3723ec336b1967b6ab5e37a/syntax_checkers/zsh/shellcheck.vim>
> to your plugin as syntax_checkers/zsh/shellcheck.vim.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scrooloose/syntastic/pull/1544#issuecomment-139470786>
> .
>



-- 
With Regards,

Yu Huang

Software Engineer,
Google Inc.

**Comment by lcd047** [comment]
So, what stops you from specifying an argument when redirecting?

**Comment by paulhybryant** [comment]
Thanks, missed that in the documents.

Added g:syntastic_zsh_shellcheck_args.

However, it still does not work as expected.

After modifying and saving a script, the
variable g:syntastic_zsh_shellcheck_args is assigned, meaning this file is
sourced.
I added some log in sh/shellcheck.vim, and no log is printed after saving
the file or :SyntasticCheck. So shellcheck is still not invoked for zsh.

On Fri, Sep 11, 2015 at 10:48 PM, LCD 047 <notifications@github.com> wrote:

> So, what stops you from specifying an argument when redirecting?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scrooloose/syntastic/pull/1544#issuecomment-139565232>
> .
>



-- 
With Regards,

Yu Huang

Software Engineer,
Google Inc.

**Comment by lcd047** [comment]
You still need to add `shellcheck` to `g:syntastic_zsh_checkers`.  You should never rely on the default list of checkers.  Except for trivial cases, it doesn't (and can't) do what you want.

**Comment by paulhybryant** [comment]
Now it works. Thank you very much.

On Sat, Sep 12, 2015 at 12:07 PM, LCD 047 <notifications@github.com> wrote:

> You still need to add shellcheck to g:syntastic_zsh_checkers. You should
> never rely on the default list of checkers. Except for trivial cases, it
> doesn't (and can't) do what you want.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scrooloose/syntastic/pull/1544#issuecomment-139711016>
> .
>



-- 
With Regards,

Yu Huang

Software Engineer,
Google Inc.

**Pull request closed without merging**
