### PR TITLE
Add `xo` checker

### PR DESCRIPTION
**Pull request by arthurvr**
Adds a new JavasScript/JSX checker called `xo`. Repo: https://github.com/sindresorhus/xo

### CODE REVIEW

**Comment by lcd047** [comment]
There seems to be a recent trend of writing various wrappers and frontends to `eslint`, so I tried to make the `eslint` checker accommodate them easier.  Please upgrade syntastic to commit c34ea89 (or later), and set:
```vim
let g:syntastic_javascript_eslint_generic = 1
let g:syntastic_javascript_eslint_exec = 'xo'
let g:syntastic_javascript_eslint_args = '--compact'
let g:syntastic_javascript_checkers = ['eslint']
```

**Comment by arthurvr** [comment]
Cool, thanks!

**Comment by sindresorhus** [comment]
> so I tried to make the eslint checker accommodate them easier

I don't really see the point of this. You're now putting the burden on the user instead of having a tiny bit of duplicated code in the repo. I would rather have made the ESLint plugin subclass-able or something, so it could be reused in the XO syntax checker. The whole point of XO over ESLint is to remove all config. Now I will have to document how the user has to manually configure the ESLint plugin, instead of just choosing the XO plugin, and be done with it...

**Comment by lcd047** [comment]
> You're now putting the burden on the user

Yes, whenever reasonably possible.  Syntastic has currently 187 checkers for 94 different filetypes, spanning almost as many different languages.  I'm currently the only active maintainer left, and I know little more than the name about most of these languages.  I'm also doing all this for free (actually, also for fun, but having fun doesn't increase my amount of available resources), in my spare time.

> instead of having a tiny bit of duplicated code in the repo.

And pretty soon end up with ~10 different copies of the same checker, subtly different to one another, and going out of synch with each other.  Thanks, but no thanks.

> I would rather have made the ESLint plugin subclass-able or something, so it could be reused in the XO syntax checker.

That's exactly what the generic thing does, except it's the other way around: the XO checker is a subclass of the ESLint one.

> The whole point of XO over ESLint is to remove all config.

This is your goal, not syntastic's (or mine, for what that's worth).

> Now I will have to document how the user has to manually configure the ESLint plugin, instead of just choosing the XO plugin, and be done with it...

Sometimes you can change the world according to your views.  Most of the time it's the other way around.

**Comment by lcd047** [comment]
@sindresorhus On a side note: you might want to take a look at #1553 for a different approach to the same problem.

**Comment by sindresorhus** [comment]
> Syntastic has currently 187 checkers for 94 different filetypes, spanning almost as many different languages. I'm currently the only active maintainer left, and I know little more than the name about most of these languages. I'm also doing all this for free (actually, also for fun, but having fun doesn't increase my amount of available resources), in my spare time. The result is what it is.

Totally understandable. That's a crazy amount of checkers. Seems like a good oppertunity to support linter plugins. In Atom/Sublime, every linter is just another package and the only thing the linter core maintainers have to care about is the linter core itself, not every imaginable plugin. Plugins are maintained by community member with knowledge of the different ecosystems. I would be happy to maintain such plugin for XO.

> That's exactly what the generic thing does, except it's the other way around: the XO checker is a subclass of the ESLint one.

That's exactly what I asked for. I might not have been clear enough. But, I would just want

```
let g:syntastic_javascript_eslint_generic = 1
let g:syntastic_javascript_eslint_exec = 'xo'
let g:syntastic_javascript_eslint_args = '--compact'
let g:syntastic_javascript_checkers = ['eslint']
```

to be *the* XO checker in this repo. So when the user choses the `xo` checker in Syntastic, it would just use the ESLint checker with the following lines. I understand you don't want to maintain almost identical full checkers, but a shortcut like this would make it a lot easier for users. I would be happy to maintain those 4 lines in this repo (they're probably never going to change).

> This is your goal, not syntastic's (or mine, for what that's worth).

I know. Just there to help you understand why I'm figting for this.

**Comment by lcd047** [comment]
> Seems like a good oppertunity to support linter plugins.

It's [already done](https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide#external).  Except Vim makes it more of a pain in the rear than Python. _shrug_

> I would be happy to maintain such plugin for XO.

All you have to do is put the plugin in the PR above a file `syntax_checkers/javascript/xo.vim`.  You'll probably also want to clean it up a little (f.i. the `IsAvailable()` function can be omitted).

**Comment by sindresorhus** [comment]
Just for posterity, I ended up making an external checker: https://github.com/sindresorhus/vim-xo

**Pull request closed without merging**
