### PR TITLE
add gometalinter syntax checker

### PR DESCRIPTION
**Pull request by joshuarubin**
Adds support for gometalinter syntax checker: https://github.com/alecthomas/gometalinter

### CODE REVIEW

**Comment by lcd047** [comment]
Thank you.  Merged, with this patch on top: 8bb535b.

**Comment by joshuarubin** [comment]
The changes you made cause this linter to stop working properly. `gometalinter` needs to be called, not with the file, but using the cwd of the file. I copied the trick used in the [`go` syntax checker](https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/go/go.vim) which is why I ended up using `self.makeprgBuild` as well.

```vim
    " The go compiler needs to either be run with an import path as an
    " argument or directly from the package directory. Since figuring out
    " the proper import path is fickle, just cwd to the package.

    let errors = SyntasticMake({
        \ 'makeprg': makeprg,
        \ 'errorformat': errorformat,
        \ 'cwd': expand('%:p:h', 1),
        \ 'env': {'GOGC': 'off'},
        \ 'defaults': {'type': 'e'} })
```

**Comment by lcd047** [comment]
> `gometalinter` needs to be called, not with the file, but using the cwd of the file.

Sadly, that isn't what `cwd` is supposed to do in `SyntasticMake()`.   Please try f2084e9.

> I copied the trick used in the [`go` syntax checker](https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/go/go.vim)

The `go` checker is a particularly oddball case, and certainly not one you want to use as a template for new checkers.  As I said: next time perhaps ask before starting to write code?

**Comment by joshuarubin** [comment]
The latest change works correctly, in fact, the way it calls gometalinter is *more* correct as some of the tools need the explicit path and weren't working correctly in my version. Thanks for the help.

**Pull request merged**
