### PR TITLE
Remove whitespace at the end of line

### PR DESCRIPTION
**Pull request by wsdjeg**

### CODE REVIEW

**Comment by lcd047** [comment]
Please make sure you're actually solving a problem before submitting patches.  Two spaces at end of lines are significant in Markdown.  Before your change:
2016-05-04-204006_897x601_scrot
After your patch:
2016-05-04-204030_895x389_scrot
Sorry, but no.

**Comment by wsdjeg** [comment]
oh，sorry.but why not use newlines ibstead of two space?

**Comment by lcd047** [comment]
Because they don't have the same effect?

**Comment by wsdjeg** [comment]
+1

**Pull request closed without merging**
