### PR TITLE
Adds the htmlhint html checker

### PR DESCRIPTION
**Pull request by inside**
The wiki page is here:
https://github.com/scrooloose/syntastic/wiki/HTML%3A---htmlhint

### CODE REVIEW

**Comment by lcd047** [comment]
This has been considered in the past and rejected (cf. #1280).  My position still stands, sorry.

> The wiki page is here:

Perhaps you should have refrained from updating the wiki until I merged your PR?

**Comment by inside** [comment]
Ok, at least I got the errorformat correctly.

Sorry for messing up the wiki. I see you already reverted the changes. Maybe I misunderstood the contribution guide: https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide#finalsteps

> Last but not least, write a short description of the checker for the wiki, and include it in your pull request.

**Comment by lcd047** [comment]
Well, the intended meaning of that paragraph is that you should write the description of the new checker in the message that announces your PR, not to change the wiki before the PR is considered...

**Comment by lcd047** [comment]
I updated the checker guide, please see 48775b5.

**Comment by inside** [comment]
Sounds clearer to me, thanks!

**Pull request closed without merging**
