### PR TITLE
Crystal external checker

### PR DESCRIPTION
**Pull request by veelenga**
To make people aware...

### CODE REVIEW

**Comment by lcd047** [comment]
Thank you.  I'd suggest changing `args` to `args_after` [here](https://github.com/rhysd/vim-crystal/blob/master/syntax_checkers/crystal/crystal.vim#L18), but otherwise, sure, merged.

**Comment by veelenga** [comment]
Found an explanation [here](https://github.com/scrooloose/syntastic/issues/970). Sure, I will! Thanks for suggestion!

**Comment by lcd047** [comment]
On second thought, this looks more appropriate:
```vim
    let makeprg = self.makeprgBuild({
        \ 'exe_after': 'run',
        \ 'args_after': '--no-build --no-color' })
```

**Comment by veelenga** [comment]
Original command looks like:
```sh
crystal run --no-build --no-color source.cr
```

Does your suggestion mean that user can pass parameter between "run" and "--no-build --no-color..." ?  Using appropriate variable:

```viml
let g:syntastic_crystal_crystal_args = '--release'
```

And after the command will look like:

```sh
crystal run --release --no-build --no-color source.cr
```

**Comment by lcd047** [comment]
Yes, that's pretty much the point.

**Comment by veelenga** [comment]
Awesome. Thanks!

**Pull request merged**
