### PR TITLE
Added configuration for jscs if it's available in the project folder

### PR DESCRIPTION
**Pull request by nemisj**
Explicit specifying config file path

### CODE REVIEW

**Comment by lcd047** [comment]
This is not a good idea.  It breaks backward compatibility for no reason, it prevents the use of a config file with a name different from `.jscsrc`, and it can be achieved with standard Vim mechanisms without patching syntastic.  It's also an attempt to use syntastic to work around a usability problem in JSCS.  Sorry, but no.

**Comment by nemisj** [comment]
@lcd047, can you please tell me how I can achieve this with standard Vim mechanisms so that i can have my jscs@2.8.0 working with .jscsrc in our project folder by using :w ?

**Comment by lcd047** [comment]
One way to do it:
```vim
autocmd BufNewFile,BufReadPre *.js let b:syntastic_javascript_jscs_args =
    \ '--config ' . findfile('.jscsrc', escape(expand('%:p:h'), ' ') . ';')
```

**Comment by nemisj** [comment]
thanks :) will useit

**Pull request closed without merging**
