### PR TITLE
Determine exact import paths by running dub for D linting.

### PR DESCRIPTION
**Pull request by w0rp**
The all but official package manager for the D programming language is DUB. DUB allows for project configuration with requirements for packages in the DUB package registry, and storing packages in the user's home directory, etc. The DUB executable knows where all of the modules for a project are,so it can build them.

Some time ago, I added an option to DUB so you can ask it for the _exact_ import paths it will use to build a project, as absolute paths, no matter where they happen to be. (`dub describe --import-paths`) This command has been in the stable versions of DUB since September. It's not always enough to simply set up a glob match for source directories in `~/.dub/packages/*/source`, etc., as package maintainers can name the source directories with any name they desire. (And _they do_...)

This pull request searches for the project root when editing D source files, where DUB is installed, and uses DUB to determine exactly where all of the modules live. In this manner, it should improve linting by always being able to locate all of the modules which are being imported.

### CODE REVIEW

**Comment by lcd047** [comment]
I presume this is a messed up rebase: your patch doesn't even make sense, let alone work as intended. :)

Regardless, I'm afraid nothing revolutionary happened since #960, my conclusion there still stands.  Running `dub` at every check is too slow, `syntastic_d_include_dirs` should be set by a shell script that runs `dub` as needed, and caches the include directories per project.  A SQLite backend might be appropriate too, for extra geek credits.  It _has_ to be written as an external script, since you don't want to reinvent `make` in Vim.  Sorry, but no. _shrug_

**Comment by w0rp** [comment]
This was absolutely not a "messed up rebase." It did precisely what I intended. It changed the `SyntaxCheckers_d_dmd_GetLocList()` function to ask `dub` for the locations of all of the import paths.

If you say it doesn't "work as intended," did you even run it with the most recent version of `dub`? It works perfectly for me. If you did you know know it is not, in fact, "too slow." `dub` can tell you exactly which import paths are being used very quickly.

The problem with setting `syntastic_d_include_dirs` is that it **doesn't work**. You end up missing out directories from the import paths, or you end up including modules which aren't in your project at all, or you end up having to manually reconfigure your global variable (which applies to every project) each time you add a new module.

Sorry, but I shall maintain a fork of this project from this point forward which actually works.

**Comment by lcd047** [comment]
> This was absolutely not a "messed up rebase." It did precisely what I intended.

The `*_GetLocList()` function is supposed to return (surprise!) a loclist.  Yours returns a list of paths.

> If you say it doesn't "work as intended," did you even run it with the most recent version of `dub`?

I didn't need to.  Did you?

**Comment by w0rp** [comment]
>The *_GetLocList() function is supposed to return (surprise!) a loclist. Yours returns a list of paths.

Right, now that actually makes sense. I'll move the production of the import paths to the part where it handles that, and then pass those on to the compiler.

**Comment by lcd047** [comment]
> I'll move the production of the import paths to the part where it handles that, and then pass those on to the compiler.

Setting `syntastic_d_include_dirs` is the API way to do that.

**Comment by w0rp** [comment]
I have amend the commit now to change the list returned from `s:_get_include_dirs`, and now that works. Thanks for letting me know. I'll keep it on my fork, and I can maybe put it in a repo for an external checker with `syntax_checkers/d/dub.vim` or something.

**Comment by lcd047** [comment]
> I have amend the commit now to change the list returned from `s:_get_include_dirs`

That breaks all other checkers that happen to use `syntastic#c#GetLocList()`.  Just saying.

**Comment by w0rp** [comment]
It checks if the `filetype` is `d` and if `dub` is executable.

**Comment by lcd047** [comment]
... and then there's a proper way to do this, without any code changes:
```vim
function Dubious(base)
    let where = escape(a:base, ' ') . ';'

    let old_suffixesadd = &suffixesadd
    let dirs = syntastic#util#unique(map(filter(
        \   findfile('dub.json', where, -1) +
        \   findfile('dub.sdl', where, -1) +
        \   findfile('package.json', where, -1),
        \ 'filereadable(v:val)'), 'fnamemodify(v:val, ":h")'))
    let &suffixesadd = old_suffixesadd

    let includes = []
    for dir in dirs
        try
            execute 'silent lcd ' . fnameescape(dir)
            call extend(includes, split(system('dub describe --import-paths', "\n")))
            silent lcd -
        catch /\m^Vim\%((\a\+)\)\=:E472/
            " evil directory is evil
        endtry
    endfor

    return syntastic#util#unique(includes)
endfunction

autocmd BufRead,BufNewFile *.d,*.di let g:syntastic_d_include_dirs = Dubious(expand('<amatch>:h', 1))
```
(not tested).

**Comment by w0rp** [comment]
@lcd047 I have added another commit which does what you pasted above, and adds a new option called `g:syntastic_d_automatic_dub_include_dirs` for turning it on in a .vimrc file, etc. Could something like this be included in the main repo? It would be nice if others could use it easily.

See here: https://github.com/w0rp/syntastic/commit/5a1db797e5bb8bfda46cd2107d6e8758750609b3

**Comment by lcd047** [comment]
> I have added another commit which does what you pasted above

The code above is supposed to be added to your `vimrc`.  Adding an `autocmd` to the checker itself is basically a time bomb.

> Could something like this be included in the main repo?

Not in the current form, but I'll eventually do it if I get positive feedback from people using the checker.

@TyOverby, @benekastah, @jakob-lundberg, @yamadapc, @cheesington, @afaur: any comments on this?

**Comment by belka-ew** [comment]
Yes this function seems to work. I only had to remove the second argument  from syntastic#util#system call, otherwise it claims about too many arguments.
dub describe --import-paths is available only in the current stable, 0.9.24: https://github.com/D-Programming-Language/dub/blob/master/CHANGELOG.md

**Pull request closed without merging**
